---
base_packages:
  - { name: 'git', state: 'present' }
  - { name: 'wget', state: 'present' }
  - { name: 'vim', state: 'present' }
  - { name: 'tmux', state: 'present' }
  - { name: 'screen', state: 'present' }
  - { name: 'python36-devel', state: 'present'} # A dependency for stormssh and just handy to have
