## Manages a JuptyerHub installation
---
- name: Setup generic environment
  hosts: hub
  tasks:
    - name: Ensure hostname is set
      become: true
      tags: ["hostname"]
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    # Add relevant keys to `ssh_public_keys`
    # in either host_vars, group_vars, or local_vars.
    - name: Manage SSH public keys
      tags: ["ssh"]
      ansible.posix.authorized_key:
        user: "{{ item.value.user }}"
        state: "{{ item.value.state }}"
        key: "{{ item.value.public_key }}"
      with_dict: "{{ ssh_public_keys }}"
      when: ssh_public_keys is defined

    - name: Install Base Packages
      become: true
      tags: ["base-packages"]
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ base_packages }}"
      when: base_packages is defined

    - name: Update Process Limits
      become: true
      community.general.pam_limits:
        dest: '{{ item.dest }}'
        domain: '{{ item.domain }}'
        limit_type: '{{ item.limit_type }}'
        limit_item: '{{ item.limit_item }}'
        value: '{{ item.value }}'
      loop:
        - dest: /etc/security/limits.d/20-nproc.conf
          domain: '*'
          limit_type: soft
          limit_item: nproc
          value: 8192
        - dest: /etc/security/limits.d/20-nproc.conf
          domain: 'root'
          limit_type: soft
          limit_item: nproc
          value: 'unlimited'

    - name: Install Python Environment
      become: true
      tags:
        - python
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      with_items:
        - python3.11
        - python3.11-pip
        - python3.11-devel

    - name: Set Python3.11 as the default
      become: true
      tags:
        - python
      community.general.alternatives:
        name: python3
        path: /usr/bin/python3.11
        link: /usr/bin/python3


    - name: Set pip3.11 as the default
      become: true
      tags:
        - python
      community.general.alternatives:
        name: pip3
        path: /usr/bin/pip3.11
        link: /usr/bin/pip3

    - name: Update Needs-Restarting python
      become: true
      tags:
        - python
      lineinfile:
        dest: /usr/bin/needs-restarting
        regexp: '^#!/usr/bin/python3$'
        line: '#!/usr/bin/python3.9'

    - name: Set SELinux as permissive
      become: true
      ansible.posix.selinux:
        policy: targeted
        state: permissive

    - name: Install firewalld
      become: true
      tags:
        - firewalld
      ansible.builtin.yum:
        name: firewalld
        state: present

    - name: Poke firewall holes
      become: true
      tags:
        - firewalld
      ansible.posix.firewalld:
        service: "{{ item.value.service }}"
        permanent: "{{ item.value.permanent | default('yes') }}"
        state: "{{ item.value.state }}"
        zone: "{{ item.value.zone }}"
      with_dict: "{{ firewalld_service_rules }}"
      when: firewalld_service_rules is defined

- name: Apply roles
  hosts: hub
  roles:
    - { role: geerlingguy.repo-epel, become: yes }
    - { role: weareinteractive.sudo, become: yes }
    - { role: devsec.hardening.ssh_hardening, become: yes }

    - role: sysstat
      become: yes

    - role: geerlingguy.apache
      become: yes
      tags:
        - httpd

    - role: dehydrated-letsencrypt
      become: yes
      tags:
        - httpd
        - ssl

    - role: zfs
      become: true
      tags:
        - zfs

    - role: zfs-snapshot
      become: true
      tags:
        - zfs

    - role: geerlingguy.docker
      become: yes
      tags:
        - docker
 
    - role: docker-extra
      become: yes
      tags:
        - docker

    - role: geerlingguy.nodejs
      become: yes
      tags:
        - nodejs
        - npm

    - role: jupyterhub
      become: yes
      tags:
        - jupyter
        - jupyterhub
 
    - role: rrsync
      become: yes
      vars:
        ansible_python_interpreter: /usr/bin/python3
      tags:
        - ssh
        - rrsync
        - backup

    - role: prometheus.prometheus.node_exporter
      become: yes
      tags:
        - prometheus
  
    - role: prometheus-target
      become: yes
      tags:
        - prometheus

