---
# This set of tasks are meant to be run only once,
# after the infrastructure has been deployed by
# Terraform.
#
- name: Initial tasks for Syzygy Infrastructure
  hosts: all
  become: true
  vars:
        ansible_ssh_pipelining: no
  tasks:
    - name: Install yum-utils for need-restarting
      yum:
        name: 'yum-utils'
        state: 'present'

    - name: Update all packages
      yum:
        name: "*"
        state: latest
      ignore_errors: true

    - name: Check needs-restarting status
      command: needs-restarting -r
      register: command_restart
      failed_when: command_restart.rc not in [0, 1]
      check_mode: no
      changed_when: false

    - name: Reboot instance
      reboot:
        reboot_timeout: 300
        pre_reboot_delay: 30
        post_reboot_delay: 30
      when: command_restart.rc == 1
