---

- name: Install and configure prometheus endpoints
  hosts: hub
  become: true
  roles:
    - role: prometheus.prometheus.node_exporter
      become: yes
      tags:
        - prometheus
  
    - role: prometheus-target
      become: yes
      tags:
        - prometheus
