---
- name: Set html target dir
  set_fact:
    syzygy_html_dir: "{{ syzygy_html_dir }}"

- name: Create the DocumentRoot
  file:
    path: '{{ item.path }}'
    state: directory
    owner: '{{ item.owner | default("root") }}'
    group: '{{ item.group | default("root") }}'
    mode: '{{ item.mode | default("0755") }}'
  with_items:
    - path: '{{ syzygy_html_dir.dest }}'
      state: directory

- name: Install HTML files
  git:
    repo: '{{ syzygy_hub_landing_page_repo }}'
    version: "{{ syzygy_landing_branch }}"
    dest: '{{ syzygy_html_dir.src }}'
    ssh_opts: "-o StrictHostKeyChecking=no"
  notify:
    - Copy landing page templates

- name: Flush handlers
  meta: flush_handlers

- name: Grab html template from host
  run_once : true
  fetch:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    flat: yes
    fail_on_missing: yes
  with_items:
    - src: '{{ syzygy_html_dir.src }}/index.html'
      dest: '/var/tmp/syzygy-html-index.html'

- name: Process html template and send results back to host
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - dest: '{{ syzygy_html_dir.dest }}/index.html'
      src: '/var/tmp/syzygy-html-index.html'
  ignore_errors: "{{ ansible_check_mode }}"

- name: Add apache config
  template:
    src: jupyter-http.conf.j2
    dest: "{{ apache_conf_path }}/jupyter-http.conf"
    owner: root
    group: root
    mode: 0644
  notify: reload apache

- name: Update DocumentRoot
  notify:
    - restart apache
  lineinfile:
    dest: '{{ apache_server_root }}/conf/httpd.conf'
    regexp: '^DocumentRoot'
    line: 'DocumentRoot "{{ syzygy_html_dir.dest }}"'
