---
- name: Install dependencies (git and make)
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - { name: 'git' }
    - { name: 'make' }

- name: ZFS Auto Snapshot
  git: 
    repo: "https://github.com/zfsonlinux/zfs-auto-snapshot.git"
    dest: "{{ zfs_auto_snap_dir }}"
    version: '{{ zfs_auto_version }}'

- name: Install ZFS Auto Snapshot
  command: make PREFIX=/usr install
  args:
    chdir: "{{ zfs_auto_snap_dir }}"
    creates: "/usr/sbin/zfs-auto-snapshot"

- name: Update snapshot retention
  replace: 
    dest: "{{ item.dest }}"
    regexp: "--keep=31"
    replace: "--keep=7"
  with_items:
    - { dest: "/etc/cron.daily/zfs-auto-snapshot" }
-


- name: Remove hourly, weekly and monthly snapshots
  file: path="{{ item.path }}" state=absent
  with_items:
    - { path: "/etc/cron.hourly/zfs-auto-snapshot" }
    - { path: "/etc/cron.weekly/zfs-auto-snapshot" }
    - { path: "/etc/cron.monthly/zfs-auto-snapshot" }
    - { path: "/etc/cron.d/zfs-auto-snapshot" }
