---
- name: Add apache vhost configuration for prometheus service
  template:
    src: observer.conf.j2
    dest: '{{ apache_conf_path }}/observer.conf'
    owner: root
    group: root
    mode: 0644
  notify: restart apache

- name: Add stats host to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    regexp: '25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?(\.|$){4}\b {{ ansible_host }}'
    line: '{{ ansible_host }} {{ metrics_host }}'
