---
# Add ansible user to docker group
- name: Add user to docker group
  user:
    name: '{{ docker_user }}'
    groups: '{{ docker_group }}'
    append: yes

- name: Check the current filesystem
  command: "lsblk -no fstype {{ openstack_ephemeral_docker_disk }}"
  when: openstack_ephemeral_docker_disk != ""
  register: filesystem_ephemeral
  check_mode: no
  changed_when: false

- name: Create an XFS filesystem on the storage
  filesystem:
    fstype: xfs
    force: yes
    dev: '{{ openstack_ephemeral_docker_disk }}'
  when: openstack_ephemeral_docker_disk != "" and "xfs" not in filesystem_ephemeral.stdout
  register: restartdocker_ephemeral

- name: Mount the ephemeral for docker
  mount:
    src: '{{ openstack_ephemeral_docker_disk}}'
    path: '/var/lib/docker'
    fstype: 'xfs'
    state: 'mounted'
  when: openstack_ephemeral_docker_disk != ""
  register: restartdocker_ephemeral

- name: Install python bindings for docker
  ansible.builtin.pip:
    name: docker

- name: Restart docker
  service: name=docker state=restarted
  when: restartdocker_ephemeral.changed

- name: update facts if docker0 is not defined
  action: setup filter="ansible_docker0"
  when: ansible_docker0 is not defined

