---
# Package name
syzygyauthenticator: syzygyauthenticator
syzygyauthenticator_repo: git+https://github.com/callysto/syzygyauthenticator
syzygyauthenticator_version: 0.1.0
syzygyauthenticator_branch: shib-ubc
syzygyauthenticator_dir: /opt/syzygyauthenticator

remote_user_authenticator: jhub_remote_user_authenticator
