---

- name: Check distro version
  shell: cat /etc/centos-release
  register: result
  when: ansible_distribution == "CentOS"
  check_mode: no
  changed_when: false

- name: Set zfs_distro_version if RedHat
  set_fact:
    zfs_distro_version: "{{ ansible_distribution_version }}"
  when: zfs_distro_version is undefined

- name: Install kernel headers
  yum:
    name: kernel-devel
    state: present
    update_cache: yes

- name: Import ZFS GPG key.
  rpm_key:
    key: "{{ zfs_repo_gpg_key_url }}"
    state: present
  register: result
  until: result is succeeded
  retries: 5
  delay: 10
  ignore_errors: "{{ ansible_check_mode }}"



- name: Install ZFS Repo
  yum:
    name: '{{ zfs_repo_url }}'
    state: present
  register: result
  until: result is succeeded
  retries: 5
  delay: 10



- name: Install zfs kernel module
  yum:
    name: zfs
    state: present
    update_cache: yes
  notify:
    - Modprobe zfs

- name: Ensure the ZFS kernel module is loaded
  modprobe:
    name: zfs

- name: Flush ZFS Handlers
  meta: flush_handlers

- name: Create tank zpool
  notify:
   - Start zfs
  command: /sbin/zpool create -f '{{ zfs_pool_name }}' {{ zfs_vdev_config }}
  args:
    creates: /tank
  when: zfs_vdev_config is defined

- name: Create ZFS home container
  command: /sbin/zfs create '{{ zfs_pool_name }}'/home
  args:
    creates: '/{{ zfs_pool_name }}/home'
  when: zfs_vdev_config is defined
